[package]
name = "fpsi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = {version = "0.13.3", features = ["yaml"]}
crossbeam-channel = "0.5"
log = "0.4"
serde = "1.0"
serde_json = "1.0"
